#!groovy
import groovy.json.JsonOutput
pipeline {
    agent {label 'master'}
    stages {

stage('remove docker'){

agent{ label 'master' }

steps{
sh 'docker rm -f tomcatqa'
}

                   
}

stage('deployment in qa'){

agent{ label 'master' }

steps{
sh 'docker run -it  -p 8089:8080 -d --name=tomcatqa malu/tomcat'
}


}

stage('slack notification'){

agent{ label 'master' }

steps{

def slackURL = 'https://hooks.slack.com/services/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'
def payload = JsonOutput.toJson([text	: text,
                                 channel   : qa-approval,
                                 username  : "webhookbot",
                                 icon_emoji: ":ghost:"])

sh 'curl -X POST --data-urlencode \'payload=${payload}\' ${slackURL}'
}


}


}
}
